//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LoanRequestSchedulerConfig = newLoanRequestSchedulerConfigTable("public", "loan_request_scheduler_config", "")

type loanRequestSchedulerConfigTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	MaximumLoanRate postgres.ColumnFloat
	AffectedFrom    postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LoanRequestSchedulerConfigTable struct {
	loanRequestSchedulerConfigTable

	EXCLUDED loanRequestSchedulerConfigTable
}

// AS creates new LoanRequestSchedulerConfigTable with assigned alias
func (a LoanRequestSchedulerConfigTable) AS(alias string) *LoanRequestSchedulerConfigTable {
	return newLoanRequestSchedulerConfigTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LoanRequestSchedulerConfigTable with assigned schema name
func (a LoanRequestSchedulerConfigTable) FromSchema(schemaName string) *LoanRequestSchedulerConfigTable {
	return newLoanRequestSchedulerConfigTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LoanRequestSchedulerConfigTable with assigned table prefix
func (a LoanRequestSchedulerConfigTable) WithPrefix(prefix string) *LoanRequestSchedulerConfigTable {
	return newLoanRequestSchedulerConfigTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LoanRequestSchedulerConfigTable with assigned table suffix
func (a LoanRequestSchedulerConfigTable) WithSuffix(suffix string) *LoanRequestSchedulerConfigTable {
	return newLoanRequestSchedulerConfigTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLoanRequestSchedulerConfigTable(schemaName, tableName, alias string) *LoanRequestSchedulerConfigTable {
	return &LoanRequestSchedulerConfigTable{
		loanRequestSchedulerConfigTable: newLoanRequestSchedulerConfigTableImpl(schemaName, tableName, alias),
		EXCLUDED:                        newLoanRequestSchedulerConfigTableImpl("", "excluded", ""),
	}
}

func newLoanRequestSchedulerConfigTableImpl(schemaName, tableName, alias string) loanRequestSchedulerConfigTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		MaximumLoanRateColumn = postgres.FloatColumn("maximum_loan_rate")
		AffectedFromColumn    = postgres.TimestampColumn("affected_from")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{IDColumn, MaximumLoanRateColumn, AffectedFromColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{MaximumLoanRateColumn, AffectedFromColumn}
	)

	return loanRequestSchedulerConfigTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		MaximumLoanRate: MaximumLoanRateColumn,
		AffectedFrom:    AffectedFromColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
