//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PromotionCampaign = newPromotionCampaignTable("public", "promotion_campaign", "")

type promotionCampaignTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	UpdatedBy   postgres.ColumnString
	Name        postgres.ColumnString
	Tag         postgres.ColumnString
	Description postgres.ColumnString
	Status      postgres.ColumnString
	Metadata    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PromotionCampaignTable struct {
	promotionCampaignTable

	EXCLUDED promotionCampaignTable
}

// AS creates new PromotionCampaignTable with assigned alias
func (a PromotionCampaignTable) AS(alias string) *PromotionCampaignTable {
	return newPromotionCampaignTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PromotionCampaignTable with assigned schema name
func (a PromotionCampaignTable) FromSchema(schemaName string) *PromotionCampaignTable {
	return newPromotionCampaignTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PromotionCampaignTable with assigned table prefix
func (a PromotionCampaignTable) WithPrefix(prefix string) *PromotionCampaignTable {
	return newPromotionCampaignTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PromotionCampaignTable with assigned table suffix
func (a PromotionCampaignTable) WithSuffix(suffix string) *PromotionCampaignTable {
	return newPromotionCampaignTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPromotionCampaignTable(schemaName, tableName, alias string) *PromotionCampaignTable {
	return &PromotionCampaignTable{
		promotionCampaignTable: newPromotionCampaignTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newPromotionCampaignTableImpl("", "excluded", ""),
	}
}

func newPromotionCampaignTableImpl(schemaName, tableName, alias string) promotionCampaignTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		UpdatedByColumn   = postgres.StringColumn("updated_by")
		NameColumn        = postgres.StringColumn("name")
		TagColumn         = postgres.StringColumn("tag")
		DescriptionColumn = postgres.StringColumn("description")
		StatusColumn      = postgres.StringColumn("status")
		MetadataColumn    = postgres.StringColumn("metadata")
		allColumns        = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, UpdatedByColumn, NameColumn, TagColumn, DescriptionColumn, StatusColumn, MetadataColumn}
		mutableColumns    = postgres.ColumnList{UpdatedByColumn, NameColumn, TagColumn, DescriptionColumn, StatusColumn, MetadataColumn}
	)

	return promotionCampaignTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		UpdatedBy:   UpdatedByColumn,
		Name:        NameColumn,
		Tag:         TagColumn,
		Description: DescriptionColumn,
		Status:      StatusColumn,
		Metadata:    MetadataColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
