//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SubmissionSheetDetail = newSubmissionSheetDetailTable("public", "submission_sheet_detail", "")

type submissionSheetDetailTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnInteger
	SubmissionSheetID postgres.ColumnInteger
	LoanRate          postgres.ColumnString
	FirmBuyingFee     postgres.ColumnFloat
	FirmSellingFee    postgres.ColumnFloat
	TransferFee       postgres.ColumnFloat
	LoanPolicies      postgres.ColumnString
	Comment           postgres.ColumnString
	CreatedAt         postgres.ColumnTimestamp
	UpdatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SubmissionSheetDetailTable struct {
	submissionSheetDetailTable

	EXCLUDED submissionSheetDetailTable
}

// AS creates new SubmissionSheetDetailTable with assigned alias
func (a SubmissionSheetDetailTable) AS(alias string) *SubmissionSheetDetailTable {
	return newSubmissionSheetDetailTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubmissionSheetDetailTable with assigned schema name
func (a SubmissionSheetDetailTable) FromSchema(schemaName string) *SubmissionSheetDetailTable {
	return newSubmissionSheetDetailTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubmissionSheetDetailTable with assigned table prefix
func (a SubmissionSheetDetailTable) WithPrefix(prefix string) *SubmissionSheetDetailTable {
	return newSubmissionSheetDetailTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubmissionSheetDetailTable with assigned table suffix
func (a SubmissionSheetDetailTable) WithSuffix(suffix string) *SubmissionSheetDetailTable {
	return newSubmissionSheetDetailTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubmissionSheetDetailTable(schemaName, tableName, alias string) *SubmissionSheetDetailTable {
	return &SubmissionSheetDetailTable{
		submissionSheetDetailTable: newSubmissionSheetDetailTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newSubmissionSheetDetailTableImpl("", "excluded", ""),
	}
}

func newSubmissionSheetDetailTableImpl(schemaName, tableName, alias string) submissionSheetDetailTable {
	var (
		IDColumn                = postgres.IntegerColumn("id")
		SubmissionSheetIDColumn = postgres.IntegerColumn("submission_sheet_id")
		LoanRateColumn          = postgres.StringColumn("loan_rate")
		FirmBuyingFeeColumn     = postgres.FloatColumn("firm_buying_fee")
		FirmSellingFeeColumn    = postgres.FloatColumn("firm_selling_fee")
		TransferFeeColumn       = postgres.FloatColumn("transfer_fee")
		LoanPoliciesColumn      = postgres.StringColumn("loan_policies")
		CommentColumn           = postgres.StringColumn("comment")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampColumn("updated_at")
		allColumns              = postgres.ColumnList{IDColumn, SubmissionSheetIDColumn, LoanRateColumn, FirmBuyingFeeColumn, FirmSellingFeeColumn, TransferFeeColumn, LoanPoliciesColumn, CommentColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{SubmissionSheetIDColumn, LoanRateColumn, FirmBuyingFeeColumn, FirmSellingFeeColumn, TransferFeeColumn, LoanPoliciesColumn, CommentColumn}
	)

	return submissionSheetDetailTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		SubmissionSheetID: SubmissionSheetIDColumn,
		LoanRate:          LoanRateColumn,
		FirmBuyingFee:     FirmBuyingFeeColumn,
		FirmSellingFee:    FirmSellingFeeColumn,
		TransferFee:       TransferFeeColumn,
		LoanPolicies:      LoanPoliciesColumn,
		Comment:           CommentColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
