//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SuggestedOfferConfig = newSuggestedOfferConfigTable("public", "suggested_offer_config", "")

type suggestedOfferConfigTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	Name          postgres.ColumnString
	Value         postgres.ColumnFloat
	ValueType     postgres.ColumnString
	Status        postgres.ColumnString
	CreatedBy     postgres.ColumnString
	LastUpdatedBy postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SuggestedOfferConfigTable struct {
	suggestedOfferConfigTable

	EXCLUDED suggestedOfferConfigTable
}

// AS creates new SuggestedOfferConfigTable with assigned alias
func (a SuggestedOfferConfigTable) AS(alias string) *SuggestedOfferConfigTable {
	return newSuggestedOfferConfigTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SuggestedOfferConfigTable with assigned schema name
func (a SuggestedOfferConfigTable) FromSchema(schemaName string) *SuggestedOfferConfigTable {
	return newSuggestedOfferConfigTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SuggestedOfferConfigTable with assigned table prefix
func (a SuggestedOfferConfigTable) WithPrefix(prefix string) *SuggestedOfferConfigTable {
	return newSuggestedOfferConfigTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SuggestedOfferConfigTable with assigned table suffix
func (a SuggestedOfferConfigTable) WithSuffix(suffix string) *SuggestedOfferConfigTable {
	return newSuggestedOfferConfigTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSuggestedOfferConfigTable(schemaName, tableName, alias string) *SuggestedOfferConfigTable {
	return &SuggestedOfferConfigTable{
		suggestedOfferConfigTable: newSuggestedOfferConfigTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newSuggestedOfferConfigTableImpl("", "excluded", ""),
	}
}

func newSuggestedOfferConfigTableImpl(schemaName, tableName, alias string) suggestedOfferConfigTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		NameColumn          = postgres.StringColumn("name")
		ValueColumn         = postgres.FloatColumn("value")
		ValueTypeColumn     = postgres.StringColumn("value_type")
		StatusColumn        = postgres.StringColumn("status")
		CreatedByColumn     = postgres.StringColumn("created_by")
		LastUpdatedByColumn = postgres.StringColumn("last_updated_by")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, NameColumn, ValueColumn, ValueTypeColumn, StatusColumn, CreatedByColumn, LastUpdatedByColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{NameColumn, ValueColumn, ValueTypeColumn, StatusColumn, CreatedByColumn, LastUpdatedByColumn}
	)

	return suggestedOfferConfigTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Name:          NameColumn,
		Value:         ValueColumn,
		ValueType:     ValueTypeColumn,
		Status:        StatusColumn,
		CreatedBy:     CreatedByColumn,
		LastUpdatedBy: LastUpdatedByColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
