//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	BlacklistSymbol = BlacklistSymbol.FromSchema(schema)
	FinancialConfiguration = FinancialConfiguration.FromSchema(schema)
	Investor = Investor.FromSchema(schema)
	InvestorAccount = InvestorAccount.FromSchema(schema)
	LoanContract = LoanContract.FromSchema(schema)
	LoanPackageOffer = LoanPackageOffer.FromSchema(schema)
	LoanPackageOfferInterest = LoanPackageOfferInterest.FromSchema(schema)
	LoanPackageRequest = LoanPackageRequest.FromSchema(schema)
	LoanPolicyTemplate = LoanPolicyTemplate.FromSchema(schema)
	LoanRequestSchedulerConfig = LoanRequestSchedulerConfig.FromSchema(schema)
	LoggedRequest = LoggedRequest.FromSchema(schema)
	OfflineOfferUpdate = OfflineOfferUpdate.FromSchema(schema)
	PromotionCampaign = PromotionCampaign.FromSchema(schema)
	SchedulerJob = SchedulerJob.FromSchema(schema)
	ScoreGroup = ScoreGroup.FromSchema(schema)
	ScoreGroupInterest = ScoreGroupInterest.FromSchema(schema)
	StockExchange = StockExchange.FromSchema(schema)
	SubmissionSheetDetail = SubmissionSheetDetail.FromSchema(schema)
	SubmissionSheetMetadata = SubmissionSheetMetadata.FromSchema(schema)
	SuggestedOffer = SuggestedOffer.FromSchema(schema)
	SuggestedOfferConfig = SuggestedOfferConfig.FromSchema(schema)
	Symbol = Symbol.FromSchema(schema)
	SymbolScore = SymbolScore.FromSchema(schema)
}
