// Code generated by mockery v2.42.2. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFlexOpenApiRepository is an autogenerated mock type for the FlexOpenApiRepository type
type MockFlexOpenApiRepository struct {
	mock.Mock
}

type MockFlexOpenApiRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlexOpenApiRepository) EXPECT() *MockFlexOpenApiRepository_Expecter {
	return &MockFlexOpenApiRepository_Expecter{mock: &_m.Mock}
}

// IsHOActive provides a mock function with given fields: ctx
func (_m *MockFlexOpenApiRepository) IsHOActive(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsHOActive")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlexOpenApiRepository_IsHOActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHOActive'
type MockFlexOpenApiRepository_IsHOActive_Call struct {
	*mock.Call
}

// IsHOActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFlexOpenApiRepository_Expecter) IsHOActive(ctx interface{}) *MockFlexOpenApiRepository_IsHOActive_Call {
	return &MockFlexOpenApiRepository_IsHOActive_Call{Call: _e.mock.On("IsHOActive", ctx)}
}

func (_c *MockFlexOpenApiRepository_IsHOActive_Call) Run(run func(ctx context.Context)) *MockFlexOpenApiRepository_IsHOActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFlexOpenApiRepository_IsHOActive_Call) Return(_a0 bool, _a1 error) *MockFlexOpenApiRepository_IsHOActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlexOpenApiRepository_IsHOActive_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockFlexOpenApiRepository_IsHOActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlexOpenApiRepository creates a new instance of MockFlexOpenApiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlexOpenApiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlexOpenApiRepository {
	mock := &MockFlexOpenApiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
