// Code generated by mockery v2.42.2. DO NOT EDIT.

package mock

import (
	context "context"
	entity "financing-offer/internal/core/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockSchedulerJobRepository is an autogenerated mock type for the SchedulerJobRepository type
type MockSchedulerJobRepository struct {
	mock.Mock
}

type MockSchedulerJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchedulerJobRepository) EXPECT() *MockSchedulerJobRepository_Expecter {
	return &MockSchedulerJobRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, job
func (_m *MockSchedulerJobRepository) Create(ctx context.Context, job entity.SchedulerJob) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.SchedulerJob) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSchedulerJobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSchedulerJobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - job entity.SchedulerJob
func (_e *MockSchedulerJobRepository_Expecter) Create(ctx interface{}, job interface{}) *MockSchedulerJobRepository_Create_Call {
	return &MockSchedulerJobRepository_Create_Call{Call: _e.mock.On("Create", ctx, job)}
}

func (_c *MockSchedulerJobRepository_Create_Call) Run(run func(ctx context.Context, job entity.SchedulerJob)) *MockSchedulerJobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.SchedulerJob))
	})
	return _c
}

func (_c *MockSchedulerJobRepository_Create_Call) Return(_a0 error) *MockSchedulerJobRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSchedulerJobRepository_Create_Call) RunAndReturn(run func(context.Context, entity.SchedulerJob) error) *MockSchedulerJobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchedulerJobRepository creates a new instance of MockSchedulerJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchedulerJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchedulerJobRepository {
	mock := &MockSchedulerJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
