with-expecter: True
packages:
  financing-offer/internal/core/loanpackagerequest/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/scoregroupinterest/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/loanoffer/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/loanofferinterest/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/symbol/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/loancontract/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/financialproduct/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/marginoperation/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/financing/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/scheduler/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/offline_offer_update/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/investor/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/investor_account/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/orderservice/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/loanpolicytemplate/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"

  financing-offer/internal/core/submissionsheet/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"


  financing-offer/internal/core/submissionsheet:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/suggested_offer/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/suggested_offer_config/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/event:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/flex/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"

  financing-offer/internal/core/odoo_service/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"

  financing-offer/internal/config/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"
  financing-offer/internal/core/promotion_campaign/repository:
    config:
      recursive: True
      all: True
      dir: test/mock
      filename: "mock_{{ .InterfaceName | lower }}.go"
      outpkg: "mock"