//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Blacklistsymbolstatus string

const (
	Blacklistsymbolstatus_Active   Blacklistsymbolstatus = "ACTIVE"
	Blacklistsymbolstatus_Inactive Blacklistsymbolstatus = "INACTIVE"
)

func (e *Blacklistsymbolstatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ACTIVE":
		*e = Blacklistsymbolstatus_Active
	case "INACTIVE":
		*e = Blacklistsymbolstatus_Inactive
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Blacklistsymbolstatus enum")
	}

	return nil
}

func (e Blacklistsymbolstatus) String() string {
	return string(e)
}
