//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/volatiletech/null/v9"
	"time"
)

type BlacklistSymbol struct {
	ID           int64 `sql:"primary_key"`
	SymbolID     int64
	AffectedFrom time.Time
	AffectedTo   null.Time
	Status       Blacklistsymbolstatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
