//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type InvestorAccount struct {
	AccountNo    string `sql:"primary_key"`
	InvestorID   string
	MarginStatus string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
