//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/volatiletech/null/v9"
	"time"
)

type LoanContract struct {
	ID                   int64 `sql:"primary_key"`
	LoanOfferInterestID  int64
	SymbolID             int64
	InvestorID           string
	AccountNo            string
	LoanID               int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	GuaranteedEndAt      null.Time
	LoanPackageAccountID int64
	LoanProductIDRef     int64
}
