//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type LoanPackageRequest struct {
	ID                 int64 `sql:"primary_key"`
	SymbolID           int64
	InvestorID         string
	AccountNo          string
	LoanRate           decimal.Decimal
	LimitAmount        decimal.Decimal
	Type               string
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	GuaranteedDuration int32
	AssetType          AssetType
	InitialRate        decimal.Decimal
	ContractSize       int64
}
