//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"github.com/volatiletech/null/v9"
	"time"
)

type LoanPackageOfferInterest struct {
	ID                      int64 `sql:"primary_key"`
	LoanPackageOfferID      int64
	ScoreGroupInterestID    *int64
	LimitAmount             decimal.Decimal
	LoanRate                decimal.Decimal
	InterestRate            decimal.Decimal
	Status                  string
	CreatedAt               time.Time
	UpdatedAt               time.Time
	LoanID                  int64
	CancelledBy             string
	CancelledAt             null.Time
	Term                    int32
	FeeRate                 decimal.Decimal
	CancelledReason         string
	AssetType               AssetType
	InitialRate             decimal.Decimal
	ContractSize            int64
	SubmissionSheetDetailID *int64
}
