//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/volatiletech/null/v9"
	"time"
)

type LoanPackageOffer struct {
	ID                   int64 `sql:"primary_key"`
	LoanPackageRequestID int64
	OfferedBy            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ExpiredAt            null.Time
	FlowType             string
}
