//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type LoanRequestSchedulerConfig struct {
	ID              int64 `sql:"primary_key"`
	MaximumLoanRate decimal.Decimal
	AffectedFrom    time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
