//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type LoanPolicyTemplate struct {
	ID                       int64 `sql:"primary_key"`
	CreatedAt                time.Time
	UpdatedAt                time.Time
	UpdatedBy                string
	Name                     string
	InterestRate             decimal.Decimal
	InterestBasis            int16
	Term                     int32
	PoolIDRef                int64
	OverdueInterest          decimal.Decimal
	AllowExtendLoanTerm      bool
	AllowEarlyPayment        bool
	PreferentialPeriod       int32
	PreferentialInterestRate decimal.Decimal
}
