//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type LoggedRequest struct {
	ID         int64 `sql:"primary_key"`
	InvestorID string
	SymbolID   int64
	Reason     string
	Request    string
	CreatedAt  time.Time
}
