//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type OfflineOfferUpdate struct {
	ID        int64 `sql:"primary_key"`
	OfferID   int64
	Status    string
	Category  string
	Note      string
	CreatedBy string
	CreatedAt time.Time
}
