//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SchedulerJob struct {
	ID           int64 `sql:"primary_key"`
	JobType      string
	JobStatus    string
	TriggerBy    string
	TrackingData string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
