//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type ScoreGroupInterest struct {
	ID           int64 `sql:"primary_key"`
	LimitAmount  decimal.Decimal
	LoanRate     decimal.Decimal
	InterestRate decimal.Decimal
	ScoreGroupID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
