//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SubmissionSheetMetadata struct {
	ID                   int64 `sql:"primary_key"`
	LoanPackageRequestID int64
	Status               string
	Creator              string
	ActionType           string
	FlowType             string
	ProposeType          string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
