//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type SubmissionSheetDetail struct {
	ID                int64 `sql:"primary_key"`
	SubmissionSheetID int64
	LoanRate          string
	FirmBuyingFee     decimal.Decimal
	FirmSellingFee    decimal.Decimal
	TransferFee       decimal.Decimal
	LoanPolicies      string
	Comment           string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
