//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type SuggestedOfferConfig struct {
	ID            int64 `sql:"primary_key"`
	Name          string
	Value         decimal.Decimal
	ValueType     string
	Status        string
	CreatedBy     string
	LastUpdatedBy string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
