//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SuggestedOffer struct {
	ID        int64 `sql:"primary_key"`
	ConfigID  int64
	AccountNo string
	Symbols   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
