//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SymbolScore struct {
	ID           int64 `sql:"primary_key"`
	SymbolID     int64
	Score        int32
	AffectedFrom time.Time
	Status       string
	Type         string
	Creator      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
