//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Symbol struct {
	ID              int64 `sql:"primary_key"`
	StockExchangeID int64
	Symbol          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AssetType       AssetType
	Status          string
	LastUpdatedBy   string
}
